-- 코드를 입력하세요
SELECT DISTINCT
    APNT_NO, 
    PT.PT_NAME,
    PT.PT_NO, 
    DR.MCDP_CD, 
    DR.DR_NAME, 
    APNT.APNT_YMD
    FROM APPOINTMENT APNT
    LEFT JOIN PATIENT PT ON APNT.PT_NO = PT.PT_NO
    LEFT JOIN DOCTOR DR ON APNT.MDDR_ID = DR.DR_ID
    WHERE APNT_CNCL_YN = 'N' AND DATE(APNT_YMD) = '2022-4-13' AND DR.MCDP_CD = 'CS'
    ORDER BY  APNT.APNT_YMD asc;